import React, { useState, useEffect } from 'react';
import DashboardLayout from '../../components/DashboardLayout';
import { api, useAuth } from '../../context/AuthContext';
import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const AiAssistantInterface = () => {
    const { user } = useAuth();
    const [batches, setBatches] = useState([]);
    
    // AI controls
    const [prompt, setPrompt] = useState('');
    const [type, setType] = useState('QUIZ'); // QUIZ, EVENT_FORM, REG_FORM, ANNOUNCEMENT, ASSIGNMENT
    const [generating, setGenerating] = useState(false);
    const [messages, setMessages] = useState([
        { sender: 'ai', text: 'Hello! I am your Smart ERP AI Assistant. I can generate MCQ quizzes, dynamic registration forms, assignments, or announcements. What would you like to build today?' }
    ]);

    // Editing states for generated structures
    const [generatedTitle, setGeneratedTitle] = useState('');
    const [generatedBody, setGeneratedBody] = useState('');
    const [selectedBatchId, setSelectedBatchId] = useState('');
    const [showPreview, setShowPreview] = useState(false);

    useEffect(() => {
        // Fetch batches to allow publishing quizzes/announcements to specific batches
        const endpoint = user?.role === 'ROLE_ADMIN' ? '/api/admins/batches' : '/api/faculties/batches';
        api.get(endpoint)
            .then(res => {
                setBatches(res.data);
                if (res.data.length > 0) setSelectedBatchId(res.data[0].id);
            })
            .catch(err => console.error('Error fetching batches', err));
    }, [user]);

    const handleSendPrompt = async (e) => {
        e.preventDefault();
        if (!prompt.trim()) return;

        const userMsg = { sender: 'user', text: `Generate a ${type.toLowerCase().replace('_', ' ')} based on prompt: "${prompt}"` };
        setMessages(prev => [...prev, userMsg]);
        setGenerating(true);
        setShowPreview(false);

        const currentPrompt = prompt;
        setPrompt('');

        try {
            const res = await api.post('/api/ai/generate', { prompt: currentPrompt, type });
            
            // Set editing state and sync with the auto-detected type from backend
            const detectedType = res.data.type || type;
            setType(detectedType);
            setGeneratedTitle(res.data.title);
            setGeneratedBody(res.data.content);
            setShowPreview(true);

            const aiMsg = {
                sender: 'ai',
                text: `I have generated the ${detectedType.toLowerCase().replace('_', ' ')}: "${res.data.title}". You can preview, edit, and publish it using the inspector panel on the right.`,
                isGeneratedResult: true
            };
            setMessages(prev => [...prev, aiMsg]);

        } catch (err) {
            console.error('Error generating with AI:', err);
            toast.error('AI text generation failed. Please try again.');
        } finally {
            setGenerating(false);
        }
    };

    const handlePublish = async () => {
        if (!generatedTitle || !generatedBody) return;
        
        try {
            // Validate JSON format first
            let parsedJson;
            try {
                parsedJson = JSON.parse(generatedBody);
            } catch (jsonErr) {
                toast.error('Invalid JSON structure. Please correct the format before publishing.');
                return;
            }

            if (type === 'QUIZ') {
                await api.post(`/api/quizzes?title=${encodeURIComponent(generatedTitle)}&batchId=${selectedBatchId}`, parsedJson);
                toast.success('MCQ Quiz successfully published to selected student batch!');
            } else if (type === 'EVENT_FORM' || type === 'REG_FORM') {
                const payload = {
                    title: generatedTitle,
                    description: `Event form dynamically generated by AI Assistant for: ${generatedTitle}`,
                    fieldsJson: JSON.stringify(parsedJson),
                    isPublished: true
                };
                await api.post('/api/forms', payload);
                toast.success('Dynamic event form successfully published. Students can view and submit responses.');
            } else if (type === 'ANNOUNCEMENT') {
                // Parse announcement
                const data = JSON.parse(generatedBody);
                
                const formData = new FormData();
                formData.append('title', generatedTitle);
                formData.append('message', data.bulletin || generatedBody);
                
                if (selectedBatchId) {
                    formData.append('targetType', 'BATCH');
                    formData.append('batchId', selectedBatchId);
                } else {
                    formData.append('targetType', 'ALL');
                }

                await api.post('/api/notifications', formData, {
                    headers: { 'Content-Type': 'multipart/form-data' }
                });
                toast.success('System announcement broadcasted successfully!');
            } else if (type === 'ASSIGNMENT') {
                const data = JSON.parse(generatedBody);
                const deadlineDate = new Date();
                deadlineDate.setDate(deadlineDate.getDate() + (data.suggestedDeadlineDays || 7));
                
                const formData = new FormData();
                formData.append('title', generatedTitle);
                formData.append('description', data.description || generatedBody);
                formData.append('deadline', deadlineDate.toISOString());
                formData.append('batchId', selectedBatchId);

                await api.post('/api/faculties/assignments', formData, {
                    headers: { 'Content-Type': 'multipart/form-data' }
                });
                toast.success('Assignment registered and assigned to selected batch!');
            }

            setShowPreview(false);
        } catch (err) {
            console.error('Publishing error:', err);
            toast.error('Failed to publish content. Please check format.');
        }
    };

    return (
        <DashboardLayout title="AI Assistant Command Center">
            <ToastContainer theme="dark" />

            <div className="grid grid-cols-1 lg:grid-cols-5 gap-8">
                {/* Left panel: ChatGPT UI */}
                <div className="lg:col-span-3 flex flex-col h-[600px] bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden relative">
                    <div className="p-4 border-b border-slate-800 bg-slate-950 flex items-center justify-between text-left">
                        <div className="flex items-center gap-2">
                            <span className="h-2 w-2 bg-emerald-500 rounded-full animate-pulse"></span>
                            <h3 className="font-bold text-white text-sm">ERP AI Co-pilot</h3>
                        </div>
                        <select
                            value={type}
                            onChange={(e) => setType(e.target.value)}
                            className="bg-slate-900 text-xs text-white border border-slate-800 rounded-lg px-2.5 py-1 focus:outline-none"
                        >
                            <option value="QUIZ">MCQ QUIZ</option>
                            <option value="EVENT_FORM">EVENT FORM</option>
                            <option value="REG_FORM">REGISTRATION FORM</option>
                            <option value="ANNOUNCEMENT">ANNOUNCEMENT</option>
                            <option value="ASSIGNMENT">ASSIGNMENT</option>
                        </select>
                    </div>

                    {/* Messages Body */}
                    <div className="flex-1 p-4 overflow-y-auto space-y-4 text-left">
                        {messages.map((m, idx) => (
                            <div key={idx} className={`flex ${m.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                                <div className={`max-w-[85%] px-4 py-2.5 rounded-2xl text-xs leading-relaxed ${
                                    m.sender === 'user'
                                        ? 'bg-emerald-500 text-slate-950 font-semibold rounded-tr-none'
                                        : 'bg-slate-950 text-slate-350 border border-slate-800/80 rounded-tl-none'
                                }`}>
                                    <p>{m.text}</p>
                                </div>
                            </div>
                        ))}
                        {generating && (
                            <div className="flex justify-start">
                                <div className="bg-slate-950 text-slate-400 border border-slate-800 rounded-2xl rounded-tl-none px-4 py-3 text-xs flex items-center gap-2">
                                    <div className="flex space-x-1">
                                        <div className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-bounce"></div>
                                        <div className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-bounce [animation-delay:0.2s]"></div>
                                        <div className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-bounce [animation-delay:0.4s]"></div>
                                    </div>
                                    <span>AI is writing database schema logs...</span>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Prompt input */}
                    <form onSubmit={handleSendPrompt} className="p-4 border-t border-slate-800 bg-slate-950/40">
                        <div className="flex items-center gap-2">
                            <input
                                type="text"
                                value={prompt}
                                onChange={(e) => setPrompt(e.target.value)}
                                placeholder={`Ask AI to generate a ${type.toLowerCase().replace('_', ' ')} (e.g. Java basics)...`}
                                className="flex-1 px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs focus:outline-none focus:ring-1 focus:ring-emerald-500 placeholder-slate-650"
                            />
                            <button
                                type="submit"
                                disabled={generating || !prompt.trim()}
                                className="p-2.5 bg-emerald-500 hover:bg-emerald-400 text-slate-950 rounded-xl transition-all shadow-lg shadow-emerald-500/10 font-bold text-xs"
                            >
                                ⚡ Send
                            </button>
                        </div>
                    </form>
                </div>

                {/* Right panel: Editor & Publisher */}
                <div className="lg:col-span-2 bg-slate-900 border border-slate-800 p-6 rounded-2xl flex flex-col h-[600px] text-left">
                    <h3 className="font-bold text-white text-base border-b border-slate-800 pb-3 mb-5">
                        Generated Code Schema Inspector
                    </h3>

                    {showPreview ? (
                        <div className="flex-1 flex flex-col justify-between overflow-hidden">
                            <div className="space-y-4 overflow-y-auto pr-1">
                                <div>
                                    <label className="block text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-2">Generated Title</label>
                                    <input
                                        type="text"
                                        value={generatedTitle}
                                        onChange={(e) => setGeneratedTitle(e.target.value)}
                                        className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs focus:outline-none"
                                    />
                                </div>

                                <div>
                                    <label className="block text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-2">JSON Structure Editor</label>
                                    <textarea
                                        value={generatedBody}
                                        onChange={(e) => setGeneratedBody(e.target.value)}
                                        rows="11"
                                        className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs font-mono focus:outline-none focus:ring-1 focus:ring-emerald-500"
                                    />
                                </div>

                                {(type === 'QUIZ' || type === 'ASSIGNMENT' || type === 'ANNOUNCEMENT') && (
                                    <div>
                                        <label className="block text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-2">Target Student Batch</label>
                                        <select
                                            value={selectedBatchId}
                                            onChange={(e) => setSelectedBatchId(e.target.value)}
                                            className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-white text-xs focus:outline-none"
                                        >
                                            {type === 'ANNOUNCEMENT' && (
                                                <option value="">All Students (Global Broadcast)</option>
                                            )}
                                            {batches.map(b => (
                                                <option key={b.id} value={b.id}>{b.name}</option>
                                            ))}
                                        </select>
                                    </div>
                                )}
                            </div>

                            <button
                                onClick={handlePublish}
                                className="w-full mt-4 py-2.5 bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 font-bold text-xs rounded-xl shadow-lg transition-all"
                            >
                                🚀 Publish & Distribute
                            </button>
                        </div>
                    ) : (
                        <div className="flex-1 flex flex-col items-center justify-center text-center">
                            <span className="text-4xl mb-4">🔮</span>
                            <h4 className="font-bold text-white text-xs">Waiting for prompt generation...</h4>
                            <p className="text-[10px] text-slate-500 max-w-[200px] mt-2">
                                Send a prompt from the AI Co-pilot panel, and its output schema will populate here for editing.
                            </p>
                        </div>
                    )}
                </div>
            </div>
        </DashboardLayout>
    );
};

export default AiAssistantInterface;
